#!/usr/bin/env python3

import re
import sys
import subprocess


def lint_stdin():
    buf = sys.stdin.read()
    process = subprocess.run(
        ["eclipse", "-e", "compile(user, [debug:off,warnings:off,load:none])."],
        capture_output=True,
        text=True,
        input=buf,
    )

    linting = process.stderr

    i = 0
    lines = []
    for line in linting.splitlines():
        if i % 3 == 0:
            lines.append(line.replace("pipe user, ", ""))
        elif i % 3 == 2:
            col = line.find("^")
            lines[-1] = re.sub(r"line (\d+):", r"line \g<1>," + f"{col}:", lines[-1])

        i += 1

    print("\n".join(lines), file=sys.stderr)

    return process.returncode


def main():
    lint_stdin()


if __name__ == "__main__":
    main()
